[package]
name = "cs2vc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
ort = { version = "1.16.3", features = ["directml"] }
windows-capture = "1.4.1"
